# Generated by Django 5.1.2 on 2024-10-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_id", models.IntegerField()),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField(null=True)),
                ("address", models.CharField(max_length=512)),
            ],
        ),
    ]
