# Generated by Django 5.1.2 on 2024-10-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_datingprofile_delete_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datingprofile",
            name="age",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="datingprofile",
            name="bio",
            field=models.TextField(blank=True, default="", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="datingprofile",
            name="gender",
            field=models.CharField(blank=True, default="", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="datingprofile",
            name="location",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
