# Generated by Django 5.1.2 on 2024-11-08 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_alter_datingprofile_age_alter_datingprofile_bio_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="datingprofile",
            name="profile_picture",
            field=models.ImageField(
                default="default_profile_pic.gif", upload_to="profile_pics/"
            ),
        ),
        migrations.AlterField(
            model_name="datingprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userprofile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
