# Generated by Django 5.1.2 on 2024-11-08 03:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("match", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["timestamp"]},
        ),
        migrations.AddField(
            model_name="message",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
